In [1]:
#import libraries
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#load the dataset
from tensorflow.keras.datasets import cifar100

In [4]:
# Load training and testing data
(X_train, y_train), (X_test, y_test) = cifar100.load_data(label_mode='fine')

In [5]:
# Print the shape of the data
print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Testing labels shape:", y_test.shape)

Training data shape: (50000, 32, 32, 3)
Testing data shape: (10000, 32, 32, 3)
Training labels shape: (50000, 1)
Testing labels shape: (10000, 1)


In [6]:
# Dataset characteristics
print(f"Training data shape: {X_train.shape}")
print(f"Test data shape: {X_test.shape}")
print(f"Number of classes: {len(np.unique(y_train))}")

Training data shape: (50000, 32, 32, 3)
Test data shape: (10000, 32, 32, 3)
Number of classes: 100


In [7]:
# Display basic statistics of the dataset
print(f"Image dimensions: {X_train.shape[1:]} (Height x Width x Channels)")
print(f"Number of training samples: {X_train.shape[0]}")
print(f"Number of test samples: {X_test.shape[0]}")

Image dimensions: (32, 32, 3) (Height x Width x Channels)
Number of training samples: 50000
Number of test samples: 10000


In [8]:
# Check distribution of labels in the training set
unique, counts = np.unique(y_train, return_counts=True)
print("Class distribution in training data:")
print(dict(zip(unique, counts)))

Class distribution in training data:
{0: 500, 1: 500, 2: 500, 3: 500, 4: 500, 5: 500, 6: 500, 7: 500, 8: 500, 9: 500, 10: 500, 11: 500, 12: 500, 13: 500, 14: 500, 15: 500, 16: 500, 17: 500, 18: 500, 19: 500, 20: 500, 21: 500, 22: 500, 23: 500, 24: 500, 25: 500, 26: 500, 27: 500, 28: 500, 29: 500, 30: 500, 31: 500, 32: 500, 33: 500, 34: 500, 35: 500, 36: 500, 37: 500, 38: 500, 39: 500, 40: 500, 41: 500, 42: 500, 43: 500, 44: 500, 45: 500, 46: 500, 47: 500, 48: 500, 49: 500, 50: 500, 51: 500, 52: 500, 53: 500, 54: 500, 55: 500, 56: 500, 57: 500, 58: 500, 59: 500, 60: 500, 61: 500, 62: 500, 63: 500, 64: 500, 65: 500, 66: 500, 67: 500, 68: 500, 69: 500, 70: 500, 71: 500, 72: 500, 73: 500, 74: 500, 75: 500, 76: 500, 77: 500, 78: 500, 79: 500, 80: 500, 81: 500, 82: 500, 83: 500, 84: 500, 85: 500, 86: 500, 87: 500, 88: 500, 89: 500, 90: 500, 91: 500, 92: 500, 93: 500, 94: 500, 95: 500, 96: 500, 97: 500, 98: 500, 99: 500}


In [9]:
#Training a logistic regression model on the CIFAR100 data

In [10]:
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)


In [12]:
#normalization

In [13]:
# Normalize pixel values to [0, 1]
X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

In [11]:
#scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_flat = scaler.fit_transform(X_train_flat)
X_test_flat = scaler.transform(X_test_flat)


In [12]:
#train the logistic regression model
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
clf.fit(X_train_flat, y_train)


c:\Users\Public\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Public\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Public\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/line

LogisticRegression(max_iter=1000, multi_class='multinomial')

In [14]:
print("Training Accuracy:", clf.score(X_train_flat, y_train))
print("Test Accuracy:", clf.score(X_test_flat, y_test))


Training Accuracy: 0.72442
Test Accuracy: 0.12


In [ ]:
#the training accuracy of the Logistic model is 72.442%
#the test accuracy of the Logistic model is 12%

In [15]:
preds = clf.predict(X_test_flat)

In [16]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,preds))

[[24  4  1 ...  0  0  0]
 [ 2 19  0 ...  0  0  0]
 [ 3  3  6 ...  3  3  2]
 ...
 [ 0  2  0 ...  7  1  1]
 [ 3  3  2 ...  0  6  1]
 [ 2  0  0 ...  1  2  2]]


In [ ]:
cm = confusion_matrix(y_test, preds, labels=clf.classes_)

# Step 4: Plot Confusion Matrix
plt.figure(figsize=(100, 100))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=clf.classes_, yticklabels=clf.classes_)
plt.title("Confusion Matrix", fontsize=16)
plt.xlabel("Predicted Labels", fontsize=14)
plt.ylabel("True Labels", fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12, rotation=0)
plt.show()


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           0       0.18      0.24      0.20       100
           1       0.17      0.19      0.18       100
           2       0.07      0.06      0.06       100
           3       0.06      0.05      0.05       100
           4       0.05      0.05      0.05       100
           5       0.07      0.06      0.07       100
           6       0.04      0.04      0.04       100
           7       0.07      0.07      0.07       100
           8       0.01      0.01      0.01       100
           9       0.22      0.26      0.24       100
          10       0.02      0.02      0.02       100
          11       0.08      0.09      0.09       100
          12       0.10      0.12      0.11       100
          13       0.04      0.04      0.04       100
          14       0.09      0.08      0.08       100
          15       0.10      0.09      0.10       100
          16       0.14      0.12      0.13       100
          17       0.19    

##### Deep learning models perform better than Traditional ML algorithms

#### The classes with higher misclassifications are 77,78,8,99

In [24]:
# Step 3: Define the baseline CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(100, activation='softmax')  # 100 output classes for CIFAR-100
])

In [25]:
#Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [26]:
# Train the model
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_test, y_test),
    verbose=2
)

Epoch 1/20


782/782 - 49s - loss: 4.2268 - accuracy: 0.0526 - val_loss: 3.7999 - val_accuracy: 0.1236 - 49s/epoch - 62ms/step
Epoch 2/20
782/782 - 33s - loss: 3.7524 - accuracy: 0.1176 - val_loss: 3.4492 - val_accuracy: 0.1754 - 33s/epoch - 42ms/step
Epoch 3/20
782/782 - 34s - loss: 3.4801 - accuracy: 0.1658 - val_loss: 3.2164 - val_accuracy: 0.2226 - 34s/epoch - 44ms/step
Epoch 4/20
782/782 - 33s - loss: 3.2936 - accuracy: 0.1954 - val_loss: 3.0488 - val_accuracy: 0.2535 - 33s/epoch - 42ms/step
Epoch 5/20
782/782 - 33s - loss: 3.1666 - accuracy: 0.2219 - val_loss: 2.9635 - val_accuracy: 0.2693 - 33s/epoch - 43ms/step
Epoch 6/20
782/782 - 35s - loss: 3.0586 - accuracy: 0.2393 - val_loss: 2.8302 - val_accuracy: 0.3000 - 35s/epoch - 45ms/step
Epoch 7/20
782/782 - 36s - loss: 2.9703 - accuracy: 0.2592 - val_loss: 2.7519 - val_accuracy: 0.3107 - 36s/epoch - 46ms/step
Epoch 8/20
782/782 - 41s - loss: 2.8799 - accuracy: 0.2735 - val_loss: 2.7004 - val_accuracy: 0.3172 - 41s/epoch - 52ms/ste

In [27]:
#Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy: {test_accuracy:.2f}")



313/313 - 7s - loss: 2.3959 - accuracy: 0.3825 - 7s/epoch - 21ms/step
Test Accuracy: 0.38


In [28]:
##ResNet architecture

In [29]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model

In [30]:
# Use ResNet50 with modifications for CIFAR-100
base_model = ResNet50(weights=None, include_top=False, input_shape=(32, 32, 3))
x = Flatten()(base_model.output)
x = Dense(512, activation='relu')(x)
x = Dense(100, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=x)

# Compile the model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [31]:
#train the model
batch_size = 64
epochs = 2

history = model.fit(
    datagen.flow(X_train, y_train, batch_size=batch_size),
    validation_data=(X_test, y_test),
    steps_per_epoch=X_train.shape[0] // batch_size,
    epochs=epochs,
    verbose=1
)


Epoch 1/2
781/781 [==============================] - 1438s 2s/step - loss: 4.1464 - accuracy: 0.0625 - val_loss: 3.8979 - val_accuracy: 0.0872
Epoch 2/2
781/781 [==============================] - 1298s 2s/step - loss: 3.7230 - accuracy: 0.1144 - val_loss: 4.0399 - val_accuracy: 0.1028


In [32]:
# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")


313/313 - 50s - loss: 4.0399 - accuracy: 0.1028 - 50s/epoch - 160ms/step
Test Accuracy: 10.28%
